# [1, 1, 1, 1, 1]
# [1, 0, 0, 0, 1]
# [1, 0, 9, 0, 1]
# [1, 0, 0, 0, 1]
# [1, 1, 1, 1, 1]

In [60]:
import numpy as np

In [45]:
x = np.ones((5,5), dtype = np.uint8)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [46]:
a,b,c,d,e = np.split(x,5)
a

array([[1, 1, 1, 1, 1]], dtype=uint8)

In [47]:
a = np.ones((5), dtype = np.uint8)
a

array([1, 1, 1, 1, 1], dtype=uint8)

In [48]:
b = np.array([1,0,0,0,1])
b

array([1, 0, 0, 0, 1])

In [49]:
c = np.array([1,0,9,0,1])
c

array([1, 0, 9, 0, 1])

In [50]:
d = np.array([1,0,0,0,1])
d

array([1, 0, 0, 0, 1])

In [51]:
e = np.ones((5), dtype = np.uint8)
e

array([1, 1, 1, 1, 1], dtype=uint8)

In [52]:
y = np.stack((a,b,c,d,e))
y

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# 2x^2 + 3y^2 - 27
# 4x^2 + y^2 + 10

In [53]:
from scipy.optimize import fsolve

In [54]:
def function(z):
    x = z[0]
    y = z[1]
    
    f = np.empty((2))
    
    f[0] = (2*(x**2)) + (3*(y**2)) - 27
    f[1] = (4*(x**2)) + (y**2) + 10
    
    return f

In [55]:
zGuess = np.array([1,1])

In [56]:
fsolve(function, zGuess)

array([2.22335584e-03, 2.66530752e+00])

# x^2 + y^2 - 20
# 2x^2 - 3y^2
# w + 5 - xy

In [61]:
def funct(z):
    x = z[0]
    y = z[1]
    w = z[2]
    
    f = np.empty((3))
    f[0] = pow(2,x) + pow(2,y) - 20
    f[1] = (2*pow(2,x)) - (3*pow(2,y))
    f[2] = w + 5 - (x*y)
    
    return f

In [66]:
zGuess = np.array([1,1,1])

In [67]:
fsolve(funct, zGuess)

array([3.5849625, 3.       , 5.7548875])