In [1]:
import numpy as np

In [10]:
x = np.random.rand(4,2,4)
x

array([[[0.31729577, 0.04777166, 0.48341422, 0.25276594],
        [0.80738487, 0.74296026, 0.53257569, 0.65562598]],

       [[0.54730361, 0.41999218, 0.69960252, 0.27802747],
        [0.45837602, 0.35898135, 0.6072707 , 0.46679747]],

       [[0.78033286, 0.65164121, 0.11364785, 0.88577027],
        [0.07144688, 0.90492217, 0.20698304, 0.3277339 ]],

       [[0.2963768 , 0.62491126, 0.26617905, 0.31211625],
        [0.14066222, 0.64856064, 0.06962458, 0.68594608]]])

In [9]:
x.ndim

3

In [13]:
y, z = np.split(x,2)

In [14]:
y

array([[[0.31729577, 0.04777166, 0.48341422, 0.25276594],
        [0.80738487, 0.74296026, 0.53257569, 0.65562598]],

       [[0.54730361, 0.41999218, 0.69960252, 0.27802747],
        [0.45837602, 0.35898135, 0.6072707 , 0.46679747]]])

In [15]:
z

array([[[0.78033286, 0.65164121, 0.11364785, 0.88577027],
        [0.07144688, 0.90492217, 0.20698304, 0.3277339 ]],

       [[0.2963768 , 0.62491126, 0.26617905, 0.31211625],
        [0.14066222, 0.64856064, 0.06962458, 0.68594608]]])

In [19]:
q = np.hsplit(z,2)
q

[array([[[0.78033286, 0.65164121, 0.11364785, 0.88577027]],
 
        [[0.2963768 , 0.62491126, 0.26617905, 0.31211625]]]),
 array([[[0.07144688, 0.90492217, 0.20698304, 0.3277339 ]],
 
        [[0.14066222, 0.64856064, 0.06962458, 0.68594608]]])]