In [1]:
import numpy as np

In [2]:
x = np.array([3,2,5])
x

array([3, 2, 5])

In [10]:
x = np.ones((3,2), dtype = int)
x

array([[1, 1],
       [1, 1],
       [1, 1]])

In [6]:
x.dtype

dtype('int32')

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
f = np.ones((3,2,4))
f
f.shape

(3, 2, 4)

In [13]:
f = np.zeros(3)
f

array([0., 0., 0.])

In [17]:
np.identity((4))


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
x = np.eye(5, k = 2)
x

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
y = np.eye(6, k = -1)
y

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [29]:
x = np.arange(10)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
x = np.arange(2,12,3)
x

array([ 2,  5,  8, 11])

#first is the start, second is the stop, third is the step

In [31]:
x = np.random.exponential()
x

0.7358415679852194

In [32]:
x = np.random.randint(2,12)
x

10

In [36]:
x = np.random.rand()
x

0.979021713909433

In [41]:
x = np.random.randint(2,10, 3)
x

array([4, 9, 5])

In [42]:
x = np.random.rand(2)
x

array([0.95337969, 0.74258714])

In [45]:
x = np.random.rand(3,4,2)
x

array([[[0.9210915 , 0.8063311 ],
        [0.21890295, 0.95034989],
        [0.04797409, 0.18615829],
        [0.72852419, 0.28996338]],

       [[0.63704235, 0.59045179],
        [0.29447004, 0.51061356],
        [0.73586814, 0.07804226],
        [0.09411747, 0.04875341]],

       [[0.37877149, 0.21935147],
        [0.1198014 , 0.86811901],
        [0.23712229, 0.65844133],
        [0.04173835, 0.84779909]]])

In [47]:
x = np.array([5,2,8])
y = np.array([4,5,7])
z = np.array([2,3,1])
m = x,y,z
m

(array([5, 2, 8]), array([4, 5, 7]), array([2, 3, 1]))

In [49]:
x = np.array([(1,2,3), (4,3,8)])
x.shape

array([[1, 2, 3],
       [4, 3, 8]])

In [53]:
x = np.array([(1,2,3), (4,3,8)])
x.ndim

2

In [54]:
x = np.array([(1,2,3), (4,3,8)])
x.reshape(6)

array([1, 2, 3, 4, 3, 8])

In [58]:
x = np.array([(1,2,3), (4,3,8)])
x.ravel()

array([1, 2, 3, 4, 3, 8])

# New class 10-6-20)