In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
# Checking for the mean of x 
x.mean()

3.0

In [9]:
y = np.random.rand(1,5)
y

array([[0.05242403, 0.89503552, 0.91912753, 0.44435369, 0.24199939]])

In [11]:
y.mean()

0.5105880337815443

In [12]:
x.dtype

dtype('int32')

In [18]:
np.median(x)

3.0

In [19]:
z = np.array([2,3,4,5], dtype = np.int8)
z

array([2, 3, 4, 5], dtype=int8)

In [21]:
m = np.array([2,3,4,5, 288], dtype = np.int8)
m

array([ 2,  3,  4,  5, 32], dtype=int8)

In [30]:
n = np.array([1,2,3,5,4,7], dtype = np.int8)
np.average(n)

3.6666666666666665

In [31]:
np.median(n)

3.5

In [32]:
n.mean()

3.6666666666666665

In [35]:
n.std(0)

1.9720265943665387

# Dot

In [36]:
np.dot(2,4)

8

In [40]:
# The process for dot is to add the product of column0 and column1 
x = np.array([2,4])
y = np.array([5,7])
np.dot(x,y)

38

In [46]:
x = np.array([[2,2], [1,2]])
y = np.array([[3,4], [3,3]])
np.dot(x,y)

array([[12, 14],
       [ 9, 10]])

In [47]:
x = np.array([[3,4,4], [2,4,5]])
y = np.array([[1,3,4], [3,5,7], [1,3,5]])
np.dot(x,y)

array([[19, 41, 60],
       [19, 41, 61]])

In [48]:
x

array([[3, 4, 4],
       [2, 4, 5]])

In [49]:
y

array([[1, 3, 4],
       [3, 5, 7],
       [1, 3, 5]])

In [61]:
a = np.array([[1,2,3], [3,4,2]], dtype= np.uint8)
b = np.array([[2,3,2], [3,4,5]])
c = np.array([[4,3,2], [4,3,7]])
d = np.array([[2,3,3], [5,8,9]])
a

array([[1, 2, 3],
       [3, 4, 2]], dtype=uint8)

In [62]:
a.sum()

15

In [63]:
a.cumsum()

array([ 1,  3,  6,  9, 13, 15], dtype=uint32)

In [64]:
np.random.rand(10,5)

array([[0.49281753, 0.03629947, 0.85318045, 0.64795145, 0.79227239],
       [0.14687114, 0.55525097, 0.74609547, 0.12406807, 0.56431719],
       [0.66159766, 0.40951249, 0.03693013, 0.47176529, 0.30008567],
       [0.55903886, 0.1896384 , 0.54364136, 0.80008403, 0.60077491],
       [0.37999098, 0.85208297, 0.0099001 , 0.71097388, 0.05858043],
       [0.36807205, 0.31927684, 0.09028779, 0.75876669, 0.36917601],
       [0.00693325, 0.03346206, 0.24406699, 0.69702019, 0.93227617],
       [0.59896417, 0.85296647, 0.8559622 , 0.06153819, 0.7272819 ],
       [0.63917237, 0.45627186, 0.53789667, 0.49931106, 0.16140256],
       [0.99546032, 0.2043738 , 0.32261101, 0.77658497, 0.85645975]])

In [70]:
v = np.random.rand(2,5)
s = np.random.rand(5,4)
np.dot(v,s)

array([[1.07327798, 0.93106596, 0.44773072, 0.96886349],
       [1.07985492, 1.05631597, 0.61675335, 1.39448043]])

In [71]:
x

array([[3, 4, 4],
       [2, 4, 5]])

In [72]:
x.vdot()

AttributeError: 'numpy.ndarray' object has no attribute 'vdot'

In [73]:
np.linalg.multi_dot([v,s])

array([[1.07327798, 0.93106596, 0.44773072, 0.96886349],
       [1.07985492, 1.05631597, 0.61675335, 1.39448043]])